MODULES += jailed
include @@THEOS@@/makefiles/common.mk

TWEAK_NAME = @@PROJECTNAME@@
BUNDLE_ID = @@PACKAGENAME@@
DISPLAY_NAME = @@FULLPROJECTNAME@@

@@PROJECTNAME@@_FILES = Tweak.xm
@@PROJECTNAME@@_IPA = @@IPA@@

include $(THEOS_MAKE_PATH)/tweak.mk
