MODULES = jailed
include @@THEOS@@/makefiles/common.mk

TWEAK_NAME = @@PROJECTNAME@@
DISPLAY_NAME = @@FULLPROJECTNAME@@
BUNDLE_ID = @@PACKAGENAME@@

@@PROJECTNAME@@_FILES = Tweak.xm
@@PROJECTNAME@@_IPA = @@IPA@@

include $(THEOS_MAKE_PATH)/tweak.mk
