include ../addon.mk

TWEAK_NAME = Cycript
Cycript_FILES = Tweak.xm

Cycript_LDFLAGS = -stdlib=libstdc++
Cycript_LIBRARIES = c++
Cycript_FRAMEWORKS = JavaScriptCore Cycript

include $(THEOS_MAKE_PATH)/tweak.mk
