ifeq ($(_THEOS_PACKAGE_FORMAT_LOADED),)
_THEOS_PACKAGE_FORMAT_LOADED := 1

export COMPRESSION := 1
ifeq ($(_THEOS_FINAL_PACKAGE),$(_THEOS_TRUE))
COMPRESSION := 9
endif

internal-package::
	$(ECHO_NOTHING)"$(IPA_SCRIPT)"$(ECHO_END)

after-package:: __THEOS_LAST_PACKAGE_FILENAME = $(THEOS_PACKAGE_DIR)/$(OUTPUT_NAME)
endif
