ifeq ($(_THEOS_PACKAGE_FORMAT_LOADED),)
_THEOS_PACKAGE_FORMAT_LOADED := 1

export COMPRESSION := 6
ifeq ($(_THEOS_FINAL_PACKAGE),$(_THEOS_TRUE))
COMPRESSION := 9
endif

internal-package::
	$(ECHO_NOTHING)"$(IPA_SCRIPT)"$(ECHO_END)
endif
